"""Go-specific analysis rules."""

from __future__ import annotations

from src.analyzer.rules import Rule

RULES: list[Rule] = [
    # ── BUGS ──────────────────────────────────────────────────────────────────
    Rule(
        id="GO-BUG001",
        category="bugs",
        severity="critical",
        message="Error return value ignored with `_`",
        pattern=r"_\s*=\s*\w+\s*\(",
        suggestion="Handle the error: `if err != nil { return err }`.",
        languages=["go"],
    ),
    Rule(
        id="GO-BUG002",
        category="bugs",
        severity="critical",
        message="Nil pointer dereference risk: result used without nil check",
        pattern=r":=\s*\w+\(\)[^;{]*\n(?!\s*if\s+\w+\s*!=\s*nil|\s*if\s+err)",
        suggestion="Check for nil before dereferencing pointer return values.",
        languages=["go"],
    ),
    Rule(
        id="GO-BUG003",
        category="bugs",
        severity="warning",
        message="Loop variable captured in goroutine closure — race condition risk",
        pattern=r"for\s+\w+\s*,?\s*\w*\s*:?=\s*range[^{]+\{[^}]*go\s+func",
        suggestion="Pass loop variable as argument to goroutine: `go func(v T) { ... }(v)`.",
        languages=["go"],
    ),
    Rule(
        id="GO-BUG004",
        category="bugs",
        severity="warning",
        message="Integer overflow risk: converting int64 to int",
        pattern=r"int\s*\(\s*\w+int64\w*\s*\)",
        suggestion="Check bounds before converting between integer types.",
        languages=["go"],
    ),
    Rule(
        id="GO-BUG005",
        category="bugs",
        severity="warning",
        message="Defer in loop: deferred calls execute at function return, not loop end",
        pattern=r"for\s+[^{]+\{[^}]*\bdefer\b",
        suggestion="Extract loop body into a function so defer executes per iteration.",
        languages=["go"],
    ),
    # ── SECURITY ──────────────────────────────────────────────────────────────
    Rule(
        id="GO-SEC001",
        category="security",
        severity="critical",
        message="`exec.Command` with shell invocation enables command injection",
        pattern=r'exec\.Command\s*\(\s*"(sh|bash|cmd)"\s*,\s*"-c"',
        suggestion="Avoid shell invocation. Pass arguments directly to exec.Command.",
        languages=["go"],
    ),
    Rule(
        id="GO-SEC002",
        category="security",
        severity="critical",
        message="SQL query built with `fmt.Sprintf` — SQL injection risk",
        pattern=r"fmt\.Sprintf\s*\([^)]*SELECT|INSERT|UPDATE|DELETE|DROP",
        suggestion="Use parameterized queries with `?` placeholders.",
        languages=["go"],
    ),
    Rule(
        id="GO-SEC003",
        category="security",
        severity="warning",
        message="Using weak TLS configuration",
        pattern=r"InsecureSkipVerify\s*:\s*true",
        suggestion="Never skip TLS verification in production.",
        languages=["go"],
    ),
    Rule(
        id="GO-SEC004",
        category="security",
        severity="warning",
        message="`math/rand` is not cryptographically secure",
        pattern=r'"math/rand"',
        suggestion='Use `crypto/rand` for security-sensitive random values.',
        languages=["go"],
    ),
    Rule(
        id="GO-SEC005",
        category="security",
        severity="critical",
        message="HTTP server with no timeouts vulnerable to slowloris attacks",
        pattern=r"http\.ListenAndServe\s*\(",
        suggestion="Use a custom http.Server with ReadTimeout, WriteTimeout, and IdleTimeout set.",
        languages=["go"],
    ),
    # ── STYLE ─────────────────────────────────────────────────────────────────
    Rule(
        id="GO-STY001",
        category="style",
        severity="suggestion",
        message="Exported identifier lacks documentation comment",
        pattern=r"^func\s+[A-Z]\w*|^type\s+[A-Z]\w*|^var\s+[A-Z]\w*|^const\s+[A-Z]\w*",
        suggestion="Add a comment starting with the identifier name: `// FuncName does ...`.",
        languages=["go"],
    ),
    Rule(
        id="GO-STY002",
        category="style",
        severity="suggestion",
        message="Using underscore in identifier name (not idiomatic Go)",
        pattern=r"func\s+\w+_\w+\s*\(|var\s+\w+_\w+\s",
        suggestion="Use camelCase naming convention in Go.",
        languages=["go"],
    ),
    # ── PERFORMANCE ───────────────────────────────────────────────────────────
    Rule(
        id="GO-PERF001",
        category="performance",
        severity="warning",
        message="Passing large struct by value — consider pointer receiver",
        pattern=r"func\s+\(\s*\w+\s+[A-Z]\w{10,}\s*\)",
        suggestion="Use a pointer receiver `*T` for large structs to avoid copying.",
        languages=["go"],
    ),
    Rule(
        id="GO-PERF002",
        category="performance",
        severity="suggestion",
        message="Slice without pre-allocated capacity grows dynamically",
        pattern=r":=\s*\[\]\w+\{\}",
        suggestion="Pre-allocate with `make([]T, 0, expectedLen)` when length is known.",
        languages=["go"],
    ),
    # ── ARCHITECTURE ──────────────────────────────────────────────────────────
    Rule(
        id="GO-ARCH001",
        category="architecture",
        severity="suggestion",
        message="TODO / FIXME comment in code",
        pattern=r"//\s*(TODO|FIXME|HACK)\b",
        suggestion="Resolve the issue or create a tracked ticket.",
        languages=["go"],
    ),
    Rule(
        id="GO-ARCH002",
        category="architecture",
        severity="warning",
        message="Panic used for non-exceptional control flow",
        pattern=r"\bpanic\s*\(",
        suggestion="Return errors instead of panicking in library code.",
        languages=["go"],
    ),
]
