"""Java-specific analysis rules."""

from __future__ import annotations

from src.analyzer.rules import Rule

RULES: list[Rule] = [
    Rule(
        id="JV-BUG001",
        category="bugs",
        severity="critical",
        message="NullPointerException risk: method called on potentially null object",
        pattern=r"\w+\.get\(\w+\)\.\w+",
        suggestion="Add null check before chaining method calls.",
        languages=["java"],
    ),
    Rule(
        id="JV-BUG002",
        category="bugs",
        severity="critical",
        message="String comparison with `==` compares references, not values",
        pattern=r'["\w]\s*==\s*"[^"]*"',
        suggestion="Use `.equals()` or `Objects.equals()` for String comparison.",
        languages=["java"],
    ),
    Rule(
        id="JV-BUG003",
        category="bugs",
        severity="warning",
        message="Empty catch block silently swallows exceptions",
        pattern=r"catch\s*\([^)]+\)\s*\{\s*\}",
        suggestion="Log the exception or re-throw a meaningful exception.",
        languages=["java"],
    ),
    Rule(
        id="JV-BUG004",
        category="bugs",
        severity="warning",
        message="`instanceof` check without cast — result unused",
        pattern=r"instanceof\s+\w+\s*;",
        suggestion="Cast the result after instanceof check or use pattern matching (Java 16+).",
        languages=["java"],
    ),
    Rule(
        id="JV-BUG005",
        category="bugs",
        severity="warning",
        message="Integer parsed without exception handling",
        pattern=r"Integer\.parseInt\s*\(",
        suggestion="Wrap in try-catch to handle NumberFormatException.",
        languages=["java"],
    ),
    Rule(
        id="JV-SEC001",
        category="security",
        severity="critical",
        message="SQL injection: query built with string concatenation",
        pattern=r'"SELECT|INSERT|UPDATE|DELETE[^"]*"\s*\+\s*\w+',
        suggestion="Use PreparedStatement with parameterized queries.",
        languages=["java"],
    ),
    Rule(
        id="JV-SEC002",
        category="security",
        severity="critical",
        message="`Runtime.exec()` with user input enables command injection",
        pattern=r"Runtime\.getRuntime\(\)\.exec\s*\(",
        suggestion="Use ProcessBuilder with a list of arguments and validate all input.",
        languages=["java"],
    ),
    Rule(
        id="JV-SEC003",
        category="security",
        severity="critical",
        message="Deserialization of untrusted data with ObjectInputStream",
        pattern=r"new\s+ObjectInputStream\s*\(",
        suggestion="Avoid deserializing untrusted data. Use JSON or implement a serialization filter.",
        languages=["java"],
    ),
    Rule(
        id="JV-SEC004",
        category="security",
        severity="warning",
        message="MD5 or SHA-1 is cryptographically weak",
        pattern=r'MessageDigest\.getInstance\s*\(\s*"(MD5|SHA-1|SHA1)"',
        suggestion="Use SHA-256 or stronger.",
        languages=["java"],
    ),
    Rule(
        id="JV-STY001",
        category="style",
        severity="suggestion",
        message="Method name should start with a lowercase letter (camelCase)",
        pattern=r"(public|private|protected)\s+\w+\s+[A-Z]\w*\s*\(",
        suggestion="Use camelCase starting with a lowercase letter for method names.",
        languages=["java"],
    ),
    Rule(
        id="JV-STY002",
        category="style",
        severity="suggestion",
        message="Constant field should be named in UPPER_SNAKE_CASE",
        pattern=r"static\s+final\s+\w+\s+[a-z][a-zA-Z0-9]+\s*=",
        suggestion="Use UPPER_SNAKE_CASE for static final constants.",
        languages=["java"],
    ),
    Rule(
        id="JV-PERF001",
        category="performance",
        severity="warning",
        message="String concatenation in loop — use StringBuilder",
        pattern=r"for\s*\([^)]*\)\s*\{[^}]*\w+\s*\+=\s*\"",
        suggestion="Use StringBuilder.append() in loops for better performance.",
        languages=["java"],
    ),
    Rule(
        id="JV-PERF002",
        category="performance",
        severity="suggestion",
        message="Creating new object in loop is expensive",
        pattern=r"for\s*\([^)]+\)\s*\{[^}]*=\s*new\s+",
        suggestion="Move object creation outside the loop if the object can be reused.",
        languages=["java"],
    ),
    Rule(
        id="JV-ARCH001",
        category="architecture",
        severity="suggestion",
        message="TODO / FIXME comment in code",
        pattern=r"//\s*(TODO|FIXME|HACK)\b",
        suggestion="Resolve the issue or create a tracked ticket.",
        languages=["java"],
    ),
]
