"""JavaScript-specific analysis rules."""

from __future__ import annotations

from src.analyzer.rules import Rule

RULES: list[Rule] = [
    # ── BUGS ──────────────────────────────────────────────────────────────────
    Rule(
        id="JS-BUG001",
        category="bugs",
        severity="critical",
        message="Using `==` instead of `===` may cause type coercion bugs",
        pattern=r"(?<!=)===?(?!=).*|[^=!]==[^=]",
        suggestion="Use strict equality `===` and strict inequality `!==`.",
        languages=["javascript"],
    ),
    Rule(
        id="JS-BUG002",
        category="bugs",
        severity="warning",
        message="Unhandled Promise rejection — missing `.catch()` or `await` in try/catch",
        pattern=r"\bPromise\.(all|race|allSettled|any)\s*\([^)]*\)\s*(?!\.catch|\.then)",
        suggestion="Chain `.catch()` or use `await` inside a try/catch block.",
        languages=["javascript"],
    ),
    Rule(
        id="JS-BUG003",
        category="bugs",
        severity="warning",
        message="Accidental global variable: variable assigned without `var`/`let`/`const`",
        pattern=r"^(?!\s*(var|let|const|function|class|import|export|if|else|for|while|return|throw|try|catch|switch|case|break|continue|//|/\*))\s*\w+\s*=\s*[^=]",
        suggestion="Always declare variables with `const` or `let`.",
        languages=["javascript"],
    ),
    Rule(
        id="JS-BUG004",
        category="bugs",
        severity="warning",
        message="Comparing NaN with `===` always returns false; use `Number.isNaN()`",
        pattern=r"[!=]==\s*NaN|NaN\s*[!=]==",
        suggestion="Use `Number.isNaN(value)` to check for NaN.",
        languages=["javascript"],
    ),
    Rule(
        id="JS-BUG005",
        category="bugs",
        severity="warning",
        message="`var` in a loop creates shared closure — use `let`",
        pattern=r"for\s*\([^)]*var\s+\w+",
        suggestion="Use `let` in for loops to create a per-iteration binding.",
        languages=["javascript"],
    ),
    Rule(
        id="JS-BUG006",
        category="bugs",
        severity="warning",
        message="setTimeout / setInterval with string argument executes arbitrary code",
        pattern=r"(setTimeout|setInterval)\s*\(\s*['\"`]",
        suggestion="Pass a function reference instead of a string to setTimeout/setInterval.",
        languages=["javascript"],
    ),
    # ── SECURITY ──────────────────────────────────────────────────────────────
    Rule(
        id="JS-SEC001",
        category="security",
        severity="critical",
        message="`eval()` executes arbitrary code — XSS and injection risk",
        pattern=r"\beval\s*\(",
        suggestion="Remove `eval()`. Use JSON.parse() for data and proper abstractions for logic.",
        languages=["javascript"],
    ),
    Rule(
        id="JS-SEC002",
        category="security",
        severity="critical",
        message="`innerHTML` assignment can lead to XSS vulnerabilities",
        pattern=r"\.innerHTML\s*=",
        suggestion="Use `textContent` for plain text or sanitize with DOMPurify before using innerHTML.",
        languages=["javascript"],
    ),
    Rule(
        id="JS-SEC003",
        category="security",
        severity="critical",
        message="`document.write()` can lead to XSS vulnerabilities",
        pattern=r"\bdocument\.write\s*\(",
        suggestion="Use DOM manipulation methods instead of document.write().",
        languages=["javascript"],
    ),
    Rule(
        id="JS-SEC004",
        category="security",
        severity="critical",
        message="Using `new Function()` executes arbitrary code",
        pattern=r"new\s+Function\s*\(",
        suggestion="Avoid dynamic code construction. Refactor to use static functions.",
        languages=["javascript"],
    ),
    Rule(
        id="JS-SEC005",
        category="security",
        severity="warning",
        message="Prototype pollution risk: assigning to `__proto__` or constructor",
        pattern=r"\[['\"__proto__['\"]|\.constructor\s*\[",
        suggestion="Validate and sanitize input before merging into objects. Use Object.create(null) for dictionaries.",
        languages=["javascript"],
    ),
    Rule(
        id="JS-SEC006",
        category="security",
        severity="warning",
        message="`location.href` set from user input can enable open redirect",
        pattern=r"location\.(href|replace|assign)\s*=",
        suggestion="Validate URLs against an allowlist before redirecting.",
        languages=["javascript"],
    ),
    # ── STYLE ─────────────────────────────────────────────────────────────────
    Rule(
        id="JS-STY001",
        category="style",
        severity="suggestion",
        message="Function name does not follow camelCase convention",
        pattern=r"function\s+[a-z]+_[a-z_]+\s*\(",
        suggestion="Rename function to camelCase per JavaScript convention.",
        languages=["javascript"],
    ),
    Rule(
        id="JS-STY002",
        category="style",
        severity="suggestion",
        message="Using `var` instead of `const`/`let`",
        pattern=r"\bvar\s+\w+",
        suggestion="Use `const` for values that won't be reassigned, `let` otherwise.",
        languages=["javascript"],
    ),
    Rule(
        id="JS-STY003",
        category="style",
        severity="suggestion",
        message="Arrow function preferred for short callbacks",
        pattern=r"\.then\s*\(\s*function\s*\(",
        suggestion="Use arrow functions `(x) => ...` for cleaner callback syntax.",
        languages=["javascript"],
    ),
    # ── PERFORMANCE ───────────────────────────────────────────────────────────
    Rule(
        id="JS-PERF001",
        category="performance",
        severity="warning",
        message="DOM query inside a loop causes repeated reflow",
        pattern=r"for\s*\([^)]*\)\s*\{[^}]*document\.(getElementById|querySelector|getElementsBy)",
        suggestion="Cache DOM references outside the loop.",
        languages=["javascript"],
    ),
    Rule(
        id="JS-PERF002",
        category="performance",
        severity="suggestion",
        message="`Array.forEach` is slower than `for...of` for large arrays",
        pattern=r"\.\bforEach\b\s*\(",
        suggestion="Consider using `for...of` when performance is critical.",
        languages=["javascript"],
    ),
    Rule(
        id="JS-PERF003",
        category="performance",
        severity="warning",
        message="Synchronous `localStorage` access in hot path may block rendering",
        pattern=r"localStorage\.(getItem|setItem|removeItem)\s*\(",
        suggestion="Consider async storage solutions for frequent access.",
        languages=["javascript"],
    ),
    # ── ARCHITECTURE ──────────────────────────────────────────────────────────
    Rule(
        id="JS-ARCH001",
        category="architecture",
        severity="suggestion",
        message="TODO / FIXME comment indicates incomplete code",
        pattern=r"//\s*(TODO|FIXME|HACK|XXX)\b",
        suggestion="Resolve the issue or create a tracked ticket.",
        languages=["javascript"],
    ),
    Rule(
        id="JS-ARCH002",
        category="architecture",
        severity="warning",
        message="Magic number used directly in code",
        pattern=r"(?<!['\"\w.])\b(?!0\b|1\b|2\b|-1\b)\d{2,}\b(?!['\"])",
        suggestion="Define as a named constant.",
        languages=["javascript"],
    ),
    Rule(
        id="JS-ARCH003",
        category="architecture",
        severity="suggestion",
        message="Console.log left in production code",
        pattern=r"\bconsole\.(log|warn|error|debug|info)\s*\(",
        suggestion="Remove console statements before deploying to production.",
        languages=["javascript"],
    ),
]
