"""Python-specific analysis rules."""

from __future__ import annotations

from src.analyzer.rules import Rule

RULES: list[Rule] = [
    # ── BUGS ──────────────────────────────────────────────────────────────────
    Rule(
        id="PY-BUG001",
        category="bugs",
        severity="critical",
        message="Bare `except:` clause catches all exceptions including SystemExit and KeyboardInterrupt",
        pattern=r"except\s*:",
        suggestion="Use `except Exception:` or catch specific exception types.",
        languages=["python"],
    ),
    Rule(
        id="PY-BUG002",
        category="bugs",
        severity="warning",
        message="Overly broad exception catch hides bugs",
        pattern=r"except\s+Exception\s*:",
        suggestion="Catch specific exceptions to avoid hiding unexpected errors.",
        languages=["python"],
    ),
    Rule(
        id="PY-BUG003",
        category="bugs",
        severity="critical",
        message="Mutable default argument can cause unexpected shared state",
        pattern=r"def\s+\w+\([^)]*=\s*(\[\]|\{\}|set\(\))",
        suggestion="Use `None` as default and initialize inside the function body.",
        languages=["python"],
    ),
    Rule(
        id="PY-BUG004",
        category="bugs",
        severity="warning",
        message="Comparing with `==` instead of `is` for None/True/False",
        pattern=r"(==|!=)\s*(None|True|False)",
        suggestion="Use `is` / `is not` for comparisons with singletons.",
        languages=["python"],
    ),
    Rule(
        id="PY-BUG005",
        category="bugs",
        severity="warning",
        message="Potential infinite loop: `while True` without visible break/return",
        pattern=r"while\s+True\s*:",
        suggestion="Ensure there is a reachable `break` or `return` statement inside the loop.",
        languages=["python"],
    ),
    Rule(
        id="PY-BUG006",
        category="bugs",
        severity="critical",
        message="Silent exception suppression with `pass` in except block",
        pattern=r"except[^:]*:\s*\n\s+pass",
        suggestion="Log the exception or re-raise it instead of silently ignoring it.",
        languages=["python"],
    ),
    Rule(
        id="PY-BUG007",
        category="bugs",
        severity="warning",
        message="Using `assert` for runtime validation (disabled with -O flag)",
        pattern=r"^\s*assert\s+",
        suggestion="Use explicit `if` checks and raise appropriate exceptions for production validation.",
        languages=["python"],
    ),
    # ── SECURITY ──────────────────────────────────────────────────────────────
    Rule(
        id="PY-SEC001",
        category="security",
        severity="critical",
        message="`eval()` executes arbitrary code — severe security risk",
        pattern=r"\beval\s*\(",
        suggestion="Avoid `eval()`. Use `ast.literal_eval()` for safe literal parsing.",
        languages=["python"],
    ),
    Rule(
        id="PY-SEC002",
        category="security",
        severity="critical",
        message="`exec()` executes arbitrary code — severe security risk",
        pattern=r"\bexec\s*\(",
        suggestion="Refactor to avoid dynamic code execution.",
        languages=["python"],
    ),
    Rule(
        id="PY-SEC003",
        category="security",
        severity="critical",
        message="`subprocess` called with `shell=True` enables command injection",
        pattern=r"subprocess\.(call|run|Popen|check_output|check_call)\s*\([^)]*shell\s*=\s*True",
        suggestion="Use `shell=False` and pass arguments as a list to prevent command injection.",
        languages=["python"],
    ),
    Rule(
        id="PY-SEC004",
        category="security",
        severity="critical",
        message="`os.system()` is vulnerable to command injection",
        pattern=r"\bos\.system\s*\(",
        suggestion="Use `subprocess.run()` with `shell=False` and a list of arguments.",
        languages=["python"],
    ),
    Rule(
        id="PY-SEC005",
        category="security",
        severity="critical",
        message="SQL query built with string formatting — SQL injection risk",
        pattern=r'(cursor\.execute|session\.execute|db\.execute)\s*\(\s*f["\']|%\s*\(',
        suggestion="Use parameterized queries / ORM methods instead of string formatting.",
        languages=["python"],
    ),
    Rule(
        id="PY-SEC006",
        category="security",
        severity="warning",
        message="`pickle.load` / `pickle.loads` can execute arbitrary code",
        pattern=r"\bpickle\.(load|loads)\s*\(",
        suggestion="Avoid deserializing untrusted pickle data. Use JSON or another safe format.",
        languages=["python"],
    ),
    Rule(
        id="PY-SEC007",
        category="security",
        severity="warning",
        message="Using MD5 or SHA1 for security purposes (cryptographically weak)",
        pattern=r"hashlib\.(md5|sha1)\s*\(",
        suggestion="Use SHA-256 or stronger (hashlib.sha256) for security-sensitive hashing.",
        languages=["python"],
    ),
    Rule(
        id="PY-SEC008",
        category="security",
        severity="critical",
        message="Flask `debug=True` in production enables remote code execution",
        pattern=r"app\.run\s*\([^)]*debug\s*=\s*True",
        suggestion="Disable debug mode in production. Set via environment variable.",
        languages=["python"],
    ),
    Rule(
        id="PY-SEC009",
        category="security",
        severity="warning",
        message="`yaml.load()` without Loader can execute arbitrary Python",
        pattern=r"\byaml\.load\s*\([^,)]+\)",
        suggestion="Use `yaml.safe_load()` instead.",
        languages=["python"],
    ),
    Rule(
        id="PY-SEC010",
        category="security",
        severity="warning",
        message="Random module is not cryptographically secure",
        pattern=r"\brandom\.(random|randint|choice|shuffle|sample)\s*\(",
        suggestion="Use `secrets` module for security-sensitive random values.",
        languages=["python"],
    ),
    # ── STYLE ─────────────────────────────────────────────────────────────────
    Rule(
        id="PY-STY001",
        category="style",
        severity="suggestion",
        message="Function name does not follow snake_case convention",
        pattern=r"def\s+[a-z][a-zA-Z0-9]*[A-Z][a-zA-Z0-9]*\s*\(",
        suggestion="Rename function to snake_case per PEP 8.",
        languages=["python"],
    ),
    Rule(
        id="PY-STY002",
        category="style",
        severity="suggestion",
        message="Class name does not follow PascalCase convention",
        pattern=r"class\s+[a-z][a-zA-Z0-9]*\s*[:(]",
        suggestion="Rename class to PascalCase per PEP 8.",
        languages=["python"],
    ),
    Rule(
        id="PY-STY003",
        category="style",
        severity="suggestion",
        message="Global variable name should be UPPER_CASE or snake_case",
        pattern=r"^[A-Z][a-z]+[A-Z]\w*\s*=",
        suggestion="Use UPPER_CASE for constants and snake_case for module-level variables.",
        languages=["python"],
    ),
    # ── PERFORMANCE ───────────────────────────────────────────────────────────
    Rule(
        id="PY-PERF001",
        category="performance",
        severity="warning",
        message="Building string with `+` in a loop is O(n²) — use `str.join()`",
        pattern=r"for\s+\w+\s+in\s+.+:\s*\n\s+\w+\s*\+=\s*['\"]",
        suggestion="Collect parts in a list and join with `''.join(parts)` after the loop.",
        languages=["python"],
    ),
    Rule(
        id="PY-PERF002",
        category="performance",
        severity="warning",
        message="`type()` check instead of `isinstance()` — slower and misses subclasses",
        pattern=r"type\s*\(\s*\w+\s*\)\s*==\s*\w+",
        suggestion="Use `isinstance(obj, Type)` which also handles inheritance.",
        languages=["python"],
    ),
    Rule(
        id="PY-PERF003",
        category="performance",
        severity="suggestion",
        message="Using list comprehension where a generator expression is more memory-efficient",
        pattern=r"sum\s*\(\s*\[",
        suggestion="Replace `sum([...])` with `sum(...)` to use a generator and save memory.",
        languages=["python"],
    ),
    Rule(
        id="PY-PERF004",
        category="performance",
        severity="warning",
        message="Global variable lookup inside hot loop — cache in local variable",
        pattern=r"for\s+.+:\s*\n(?:\s+.*\n)*?\s+global\s+",
        suggestion="Assign the global to a local variable before the loop.",
        languages=["python"],
    ),
    # ── ARCHITECTURE ──────────────────────────────────────────────────────────
    Rule(
        id="PY-ARCH001",
        category="architecture",
        severity="warning",
        message="Magic number used directly in code — use a named constant",
        pattern=r"(?<!['\"\w.])\b(?!0\b|1\b|2\b|-1\b)\d{2,}\b(?!['\"])",
        suggestion="Define a named constant at the module level.",
        languages=["python"],
    ),
    Rule(
        id="PY-ARCH002",
        category="architecture",
        severity="suggestion",
        message="Deeply nested code (4+ levels) reduces readability",
        pattern=r"^(\s{16}|\t{4})",
        suggestion="Extract nested logic into helper functions.",
        languages=["python"],
    ),
    Rule(
        id="PY-ARCH003",
        category="architecture",
        severity="suggestion",
        message="TODO / FIXME / HACK comment indicates incomplete or workaround code",
        pattern=r"#\s*(TODO|FIXME|HACK|XXX|BUG)\b",
        suggestion="Resolve the issue or create a tracked ticket.",
        languages=["python"],
    ),
    Rule(
        id="PY-ARCH004",
        category="architecture",
        severity="warning",
        message="Returning `None` explicitly is redundant — function already returns None implicitly",
        pattern=r"return\s+None\s*$",
        suggestion="Omit the explicit `return None` at the end of a function.",
        languages=["python"],
    ),
    Rule(
        id="PY-ARCH005",
        category="architecture",
        severity="suggestion",
        message="Unused import detected",
        pattern=r"^import\s+\w+\s*$|^from\s+\S+\s+import\s+\w+\s*$",
        suggestion="Remove unused imports to keep the module clean.",
        languages=["python"],
    ),
]
