"""Ruby-specific analysis rules."""

from __future__ import annotations

from src.analyzer.rules import Rule

RULES: list[Rule] = [
    Rule(
        id="RB-BUG001",
        category="bugs",
        severity="critical",
        message="Mass assignment without strong params — may allow unintended attribute updates",
        pattern=r"\w+\.update\s*\(\s*params\[|\.create\s*\(\s*params\[",
        suggestion="Use strong parameters: `params.require(:model).permit(:field1, :field2)`.",
        languages=["ruby"],
    ),
    Rule(
        id="RB-BUG002",
        category="bugs",
        severity="warning",
        message="Rescue catching all exceptions including SystemExit",
        pattern=r"rescue\s*$|rescue\s*Exception\s*=>",
        suggestion="Rescue specific exception types.",
        languages=["ruby"],
    ),
    Rule(
        id="RB-BUG003",
        category="bugs",
        severity="warning",
        message="Using `==` to compare symbols — consider `equal?` for identity",
        pattern=r":\w+\s*==\s*:\w+",
        suggestion="Use `equal?` for object identity or ensure consistent symbol usage.",
        languages=["ruby"],
    ),
    Rule(
        id="RB-SEC001",
        category="security",
        severity="critical",
        message="`eval()` executes arbitrary code",
        pattern=r"\beval\s*\(",
        suggestion="Remove eval(). Use proper Ruby abstractions.",
        languages=["ruby"],
    ),
    Rule(
        id="RB-SEC002",
        category="security",
        severity="critical",
        message="`send()` with user input can call arbitrary methods",
        pattern=r"\.send\s*\(\s*params|\.send\s*\(\s*\w+_param",
        suggestion="Whitelist allowed method names before using send().",
        languages=["ruby"],
    ),
    Rule(
        id="RB-SEC003",
        category="security",
        severity="critical",
        message="SQL injection: string interpolation in SQL query",
        pattern=r'where\s*\(\s*"[^"]*#\{|find_by_sql\s*\(\s*"[^"]*#\{',
        suggestion="Use ActiveRecord parameterized queries: `where('col = ?', val)`.",
        languages=["ruby"],
    ),
    Rule(
        id="RB-SEC004",
        category="security",
        severity="critical",
        message="Command injection: user input passed to backtick or system()",
        pattern=r'`[^`]*#\{|\bsystem\s*\([^)]*#\{',
        suggestion="Use Open3 and never interpolate user input into shell commands.",
        languages=["ruby"],
    ),
    Rule(
        id="RB-STY001",
        category="style",
        severity="suggestion",
        message="Method name should use snake_case",
        pattern=r"def\s+[a-z]+[A-Z]\w*",
        suggestion="Use snake_case for Ruby method names.",
        languages=["ruby"],
    ),
    Rule(
        id="RB-STY002",
        category="style",
        severity="suggestion",
        message="Trailing whitespace in code",
        pattern=r"[ \t]+$",
        suggestion="Remove trailing whitespace.",
        languages=["ruby"],
    ),
    Rule(
        id="RB-PERF001",
        category="performance",
        severity="warning",
        message="N+1 query: database call in a loop",
        pattern=r"\.each\s*\{[^}]*\.find\(|\.each\s*\{[^}]*\.where\(",
        suggestion="Use eager loading: `includes(:association)` to avoid N+1 queries.",
        languages=["ruby"],
    ),
    Rule(
        id="RB-ARCH001",
        category="architecture",
        severity="suggestion",
        message="TODO / FIXME comment in code",
        pattern=r"#\s*(TODO|FIXME|HACK)\b",
        suggestion="Resolve the issue or create a tracked ticket.",
        languages=["ruby"],
    ),
]
