"""Rust-specific analysis rules."""

from __future__ import annotations

from src.analyzer.rules import Rule

RULES: list[Rule] = [
    Rule(
        id="RS-BUG001",
        category="bugs",
        severity="critical",
        message="`unwrap()` on Result/Option will panic if value is Err/None",
        pattern=r"\.(unwrap)\s*\(\s*\)",
        suggestion="Use `?`, `unwrap_or`, `unwrap_or_else`, or pattern match instead of unwrap().",
        languages=["rust"],
    ),
    Rule(
        id="RS-BUG002",
        category="bugs",
        severity="critical",
        message="`expect()` will panic with a message — use proper error handling",
        pattern=r"\.expect\s*\(",
        suggestion="Use `?` to propagate errors or handle them explicitly.",
        languages=["rust"],
    ),
    Rule(
        id="RS-BUG003",
        category="bugs",
        severity="warning",
        message="Integer overflow possible in release mode (unchecked arithmetic)",
        pattern=r"\bas\s+u(8|16|32|64|128|size)\b",
        suggestion="Use checked_add/checked_sub or saturating arithmetic for safety.",
        languages=["rust"],
    ),
    Rule(
        id="RS-SEC001",
        category="security",
        severity="critical",
        message="`unsafe` block bypasses Rust's memory safety guarantees",
        pattern=r"\bunsafe\s*\{",
        suggestion="Minimize unsafe blocks. Document invariants and provide safe wrappers.",
        languages=["rust"],
    ),
    Rule(
        id="RS-SEC002",
        category="security",
        severity="warning",
        message="`std::mem::transmute` is highly unsafe",
        pattern=r"\bmem::transmute\s*\(",
        suggestion="Use safer alternatives like `as` casting or `from_bytes`.",
        languages=["rust"],
    ),
    Rule(
        id="RS-SEC003",
        category="security",
        severity="critical",
        message="`Command::new` with shell may allow command injection",
        pattern=r'Command::new\s*\(\s*"(sh|bash|cmd)"\s*\)',
        suggestion="Avoid shell invocation; pass arguments directly to the command.",
        languages=["rust"],
    ),
    Rule(
        id="RS-PERF001",
        category="performance",
        severity="warning",
        message="Cloning value unnecessarily in performance-sensitive code",
        pattern=r"\.clone\(\)",
        suggestion="Consider borrowing instead of cloning to avoid heap allocation.",
        languages=["rust"],
    ),
    Rule(
        id="RS-PERF002",
        category="performance",
        severity="suggestion",
        message="`String::new()` followed by push_str — use `to_string()` or format! directly",
        pattern=r'String::new\(\)\s*;\s*\n\s*\w+\.push_str',
        suggestion="Use `let s = format!(...);` or `let s = value.to_string();`.",
        languages=["rust"],
    ),
    Rule(
        id="RS-STY001",
        category="style",
        severity="suggestion",
        message="Function name uses camelCase instead of snake_case",
        pattern=r"fn\s+[a-z]+[A-Z]\w*\s*\(",
        suggestion="Use snake_case for function names per Rust convention.",
        languages=["rust"],
    ),
    Rule(
        id="RS-ARCH001",
        category="architecture",
        severity="suggestion",
        message="TODO / FIXME comment indicates incomplete code",
        pattern=r"//\s*(TODO|FIXME|HACK|UNIMPLEMENTED)\b",
        suggestion="Resolve the issue or use `todo!()` macro with a tracking issue.",
        languages=["rust"],
    ),
    Rule(
        id="RS-ARCH002",
        category="architecture",
        severity="warning",
        message="`todo!()` macro will panic at runtime",
        pattern=r"\btodo!\s*\(\s*\)",
        suggestion="Implement the missing functionality before production deployment.",
        languages=["rust"],
    ),
    Rule(
        id="RS-ARCH003",
        category="architecture",
        severity="warning",
        message="`unimplemented!()` macro will panic at runtime",
        pattern=r"\bunimplemented!\s*\(\s*\)",
        suggestion="Implement the missing functionality or return an error.",
        languages=["rust"],
    ),
]
