"""Solidity-specific analysis rules."""

from __future__ import annotations

from src.analyzer.rules import Rule

RULES: list[Rule] = [
    Rule(
        id="SOL-BUG001",
        category="bugs",
        severity="critical",
        message="Reentrancy vulnerability: state changed after external call",
        pattern=r"\.call\{[^}]*\}\s*\([^)]*\)[^;]*;\s*\n(?:\s*[^;]+;\s*\n)*\s*\w+\s*[+-]?=",
        suggestion="Follow checks-effects-interactions pattern: update state before external calls.",
        languages=["solidity"],
    ),
    Rule(
        id="SOL-BUG002",
        category="bugs",
        severity="critical",
        message="Integer overflow/underflow: use SafeMath or Solidity 0.8+",
        pattern=r"uint\d*\s+\w+\s*=\s*\w+\s*[+\-\*]\s*\w+",
        suggestion="Use Solidity 0.8+ (built-in overflow checks) or OpenZeppelin SafeMath.",
        languages=["solidity"],
    ),
    Rule(
        id="SOL-BUG003",
        category="bugs",
        severity="critical",
        message="Using `tx.origin` for authentication is phishable",
        pattern=r"\btx\.origin\b",
        suggestion="Use `msg.sender` for authentication instead of tx.origin.",
        languages=["solidity"],
    ),
    Rule(
        id="SOL-BUG004",
        category="bugs",
        severity="warning",
        message="Unchecked return value from `.call()`",
        pattern=r"\.call\{[^}]*\}\s*\([^)]*\)\s*;",
        suggestion="Check the boolean return value: `(bool success, ) = addr.call{...}(...); require(success);`.",
        languages=["solidity"],
    ),
    Rule(
        id="SOL-BUG005",
        category="bugs",
        severity="warning",
        message="Timestamp dependency for critical logic (block.timestamp can be manipulated)",
        pattern=r"\bblock\.timestamp\b",
        suggestion="Avoid using block.timestamp for randomness or precise timing.",
        languages=["solidity"],
    ),
    Rule(
        id="SOL-SEC001",
        category="security",
        severity="critical",
        message="Selfdestruct can permanently destroy the contract",
        pattern=r"\bselfdestruct\s*\(|\bsuicide\s*\(",
        suggestion="Avoid selfdestruct. If needed, protect with strong access control.",
        languages=["solidity"],
    ),
    Rule(
        id="SOL-SEC002",
        category="security",
        severity="critical",
        message="Delegatecall to untrusted address is extremely dangerous",
        pattern=r"\.delegatecall\s*\(",
        suggestion="Only delegatecall to trusted, audited contracts.",
        languages=["solidity"],
    ),
    Rule(
        id="SOL-SEC003",
        category="security",
        severity="warning",
        message="Function visibility not explicitly set",
        pattern=r"function\s+\w+\s*\([^)]*\)\s*(?!public|private|internal|external)",
        suggestion="Always explicitly set function visibility (public/private/internal/external).",
        languages=["solidity"],
    ),
    Rule(
        id="SOL-SEC004",
        category="security",
        severity="warning",
        message="Using `block.blockhash` for randomness is predictable",
        pattern=r"\bblockhash\s*\(\s*block\.number",
        suggestion="Use Chainlink VRF or a commit-reveal scheme for on-chain randomness.",
        languages=["solidity"],
    ),
    Rule(
        id="SOL-PERF001",
        category="performance",
        severity="warning",
        message="Storing data in storage when memory is sufficient (high gas cost)",
        pattern=r"function\s+\w+[^{]+\{[^}]*\w+\s+storage\s+\w+\s*=",
        suggestion="Use `memory` keyword for variables not needing persistence to reduce gas.",
        languages=["solidity"],
    ),
    Rule(
        id="SOL-PERF002",
        category="performance",
        severity="suggestion",
        message="Loop over dynamic array in storage: unbounded gas cost",
        pattern=r"for\s*\([^)]*;\s*\w+\s*<\s*\w+\.length",
        suggestion="Set a maximum iteration limit or use off-chain computation.",
        languages=["solidity"],
    ),
    Rule(
        id="SOL-ARCH001",
        category="architecture",
        severity="warning",
        message="Missing access control on sensitive function",
        pattern=r"function\s+\w*(withdraw|transfer|mint|burn|upgrade)\w*\s*\([^)]*\)\s*external",
        suggestion="Add `onlyOwner` or role-based access control modifiers.",
        languages=["solidity"],
    ),
    Rule(
        id="SOL-ARCH002",
        category="architecture",
        severity="suggestion",
        message="TODO / FIXME comment in contract",
        pattern=r"//\s*(TODO|FIXME|HACK)\b",
        suggestion="Resolve before deploying to production.",
        languages=["solidity"],
    ),
]
